"""changed team id to team

Revision ID: 723d0f878b09
Revises: e9ca39452f1c
Create Date: 2023-09-28 10:47:08.950528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723d0f878b09'
down_revision = 'e9ca39452f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coaches_team_id_teams', type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_team_id_teams', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_players_team_id_teams', 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_coaches_team_id_teams', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###
