"""fixing tables

Revision ID: b375c54b4e70
Revises: d4ff13997f77
Create Date: 2023-10-06 12:27:40.337125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b375c54b4e70'
down_revision = 'd4ff13997f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_coaches_team_name_teams', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_coaches_team_id_teams'), 'teams', ['team_id'], ['id'])
        batch_op.drop_column('team_name')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_players_team_name_teams', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_players_team_id_teams'), 'teams', ['team_id'], ['id'])
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_players_team_id_teams'), type_='foreignkey')
        batch_op.create_foreign_key('fk_players_team_name_teams', 'teams', ['team_name'], ['name'])
        batch_op.drop_column('team_id')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_coaches_team_id_teams'), type_='foreignkey')
        batch_op.create_foreign_key('fk_coaches_team_name_teams', 'teams', ['team_name'], ['name'])
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
