"""changed team id to team_name

Revision ID: d4ff13997f77
Revises: 723d0f878b09
Create Date: 2023-09-28 10:48:38.682164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ff13997f77'
down_revision = '723d0f878b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_coaches_team_name_teams'), 'teams', ['team_name'], ['name'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_players_team_name_teams'), 'teams', ['team_name'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_players_team_name_teams'), type_='foreignkey')
        batch_op.drop_column('team_name')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coaches_team_name_teams'), type_='foreignkey')
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###
