"""added one to many

Revision ID: e9ca39452f1c
Revises: 8ed0869ba681
Create Date: 2023-09-28 09:35:53.137817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ca39452f1c'
down_revision = '8ed0869ba681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_coaches_team_id_teams'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_players_team_id_teams'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_player_id_players', type_='foreignkey')
        batch_op.drop_constraint('fk_teams_coach_id_coaches', type_='foreignkey')
        batch_op.drop_column('player_id')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_teams_coach_id_coaches', 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key('fk_teams_player_id_players', 'players', ['player_id'], ['id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_players_team_id_teams'), type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coaches_team_id_teams'), type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
